package:
  name: edges
  version: {{ environ['VERSION'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  script_env:
    - VERSION
    - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools
  run:
    - bw2calc
    - bw2data
    - bw2io
    - constructive_geometries

test:
  imports:
    - edges

about:
  home: https://github.com/Laboratory-for-Energy-Systems-Analysis/edges
  license: MIT License
  summary: 'Country-specific characterization factors for the LCA framework Brightway2'
license_family: MIT
